name: Update address database

on:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -m preprocess
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
          token: ${{ secrets.PAT }}
          commit-message: Update database
          labels:
            - database-update
          title: Update database
          body: |
            - Update database
          branch: update-dependencies
